### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './run.sh'

### ISSUE THREAD

**Issue by deepqd98** [DeepAlchemist/deep-person-search#2]
Traceback (most recent call last):
  File "main.py", line 282, in <module>
    cfg = Config().parse()
  File "/home/deep-person-search-master/lib/cfg/config.py", line 108, in parse
    self.print_options(cfg)
  File "/home/deep-person-search-master/lib/cfg/config.py", line 92, in print_options
    shutil.copy("./run.sh", cfg.expr_dir)
  File "/home/qd/anaconda3/envs/dps/lib/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/home/qd/anaconda3/envs/dps/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: './run.sh'

I cannot find "run.sh" in your project, how to solve the problem?

**Comment by deepalchemist** [comment]
Hi, you can create the run.sh file, i.e., deep-person-search/run.sh
or just remove the line 92 of config.py.
